apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-https-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-https-app
  template:
    metadata:
      labels:
        app: simple-https-app
    spec:
      containers:
      - name: simple-https-app
        image: jitender1987/autozonecasestudy:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "50m"
        ports:
        - containerPort: 3000
        livenessProbe:
            httpGet:
              path: /health/liveness
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
        readinessProbe:
            httpGet:
              path: /health/readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
        startupProbe:
            httpGet:
              path: /health/startup
              port: 3000
            failureThreshold: 30
            periodSeconds: 30
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/ssl/certs
          readOnly: true
        - name: pvc-volume
          mountPath: /temp
      volumes: 
      - name: tls-certs
        secret:
          secretName: my-tls-secret
      - name: pvc-volume
        persistentVolumeClaim:
          claimName: simple-https-app-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: simple-https-app-service
spec:
  selector:
    app: simple-https-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000
      nodePort: 31110
  type: LoadBalancer
