apiVersion: v1
kind: PersistentVolume
metadata:
  name: simple-https-app-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /var/lib/webapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: simple-https-app-pvc
spec:
   storageClassName: standard
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 500Mi